export const IRAQI_GOVERNORATES = {
    "Al Anbar": ["Ramadi", "Fallujah", "Al-Qa'im", "Hit", "Haditha"],
    "Babylon": ["Hillah", "Musayyib", "Hashimiyah", "Mahawil"],
    "Baghdad": ["Karkh", "Rusafa", "Sadr City", "Adhamiyah", "Mansour", "Karrada"],
    "Basra": ["Basra City", "Al-Zubair", "Al-Qurnah", "Abu Al-Khaseeb", "Faw"],
    "Dhi Qar": ["Nasiriyah", "Al-Rifai", "Shatrah", "Suq al-Shuyukh"],
    "Al-Qadisiyyah": ["Diwaniyah", "Afaq", "Hamza", "Shamiya"],
    "Diyala": ["Baqubah", "Muqdadiyah", "Khanaqin", "Balad Ruz"],
    "Duhok": ["Duhok City", "Zakho", "Amedi", "Akre"],
    "Erbil": ["Erbil City", "Soran", "Shaqlawa", "Koya"],
    "Karbala": ["Karbala City", "Ain Al-Tamur", "Al-Hindiya"],
    "Kirkuk": ["Kirkuk City", "Hawija", "Daquq", "Dibis"],
    "Maysan": ["Amarah", "Ali Al-Gharbi", "Al-Majar Al-Kabir", "Qal'at Saleh"],
    "Muthanna": ["Samawah", "Rumaitha", "Al-Khidhir"],
    "Najaf": ["Najaf City", "Kufa", "Manathera"],
    "Nineveh": ["Mosul", "Tel Afar", "Sinjar", "Al-Hamdaniya", "Shekhan"],
    "Saladin": ["Tikrit", "Samarra", "Balad", "Tuz Khurmatu", "Dujail"],
    "Sulaymaniyah": ["Sulaymaniyah City", "Chamchamal", "Halabja", "Ranya", "Penjwen"],
    "Wasit": ["Kut", "Al-Hai", "Al-Suwaira", "Badra", "Numaniyah"]
};

export const MEDICAL_SPECIALTIES = [
    "Allergy and Immunology",
    "Anesthesiology",
    "Cardiology",
    "Dermatology",
    "Emergency Medicine",
    "Endocrinology",
    "Family Medicine",
    "Gastroenterology",
    "General Surgery",
    "Geriatrics",
    "Hematology",
    "Infectious Disease",
    "Internal Medicine",
    "Nephrology",
    "Neurology",
    "Neurosurgery",
    "Obstetrics and Gynecology (OB/GYN)",
    "Oncology",
    "Ophthalmology",
    "Orthopedic Surgery",
    "Otolaryngology (ENT)",
    "Pathology",
    "Pediatrics",
    "Plastic Surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Urology",
];
