import type { Translations } from '@/types';

export const translations: Translations = {
  en: {
    appName: 'Spirit',
    appSubtitle: 'For Managing Centers and Hospitals',
    auth: {
      login: 'Login',
      signup: 'Sign Up',
      username: 'Username',
      password: 'Password',
      email: 'Email',
      phoneNumber: 'Phone Number (Optional)',
      loginCta: 'Log into your account',
      signupCta: 'Create a new account',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      logout: 'Logout',
      signupSuccessTitle: 'Account Created',
      signupSuccessDesc: 'Your account has been created successfully! You can now log in.',
      signupFailedTitle: 'Signup Failed',
      signupFailedDesc: 'A user with this email or phone number already exists.',
    },
    header: {
      searchPlaceholder: 'Search by name, specialty, address...',
      addDoctor: 'Add Doctor',
      filterPartners: 'Filter Partners',
      totalDoctors: 'Doctors',
      totalPartners: 'Partners',
      adminDashboard: 'Admin Dashboard',
      partnerDashboard: 'Partner Dashboard',
      gridView: 'Grid View',
      listView: 'List View',
      sortBy: 'Sort by',
      sort: {
        name: 'Name',
        date: 'Date Added',
        address: 'Address',
      },
      translateAll: 'Translate All Cards',
      enterFullscreen: 'Enter Fullscreen',
      exitFullscreen: 'Exit Fullscreen',
    },
    doctorCard: {
      partner: 'Partner',
      referrals: 'Referrals',
      commission: 'Commission',
      usd: 'USD',
      setMyLocation: 'Set My Location',
      call: 'Call',
      map: 'Map',
      edit: 'Edit',
      delete: 'Delete',
      availability: 'Availability',
      days: {
        Sat: 'Sat',
        Sun: 'Sun',
        Mon: 'Mon',
        Tue: 'Tue',
        Wed: 'Wed',
        Thu: 'Thu',
        Fri: 'Fri',
      },
      notSet: 'Not Set',
      viewCases: 'View Referral Cases',
    },
    doctorForm: {
      addTitle: 'Add New Doctor',
      editTitle: 'Edit Doctor Details',
      name: 'Doctor Name',
      specialty: 'Specialty',
      phoneNumber: 'Phone Number',
      clinicAddress: 'Clinic Address',
      clinicCardImage: 'Clinic Card Image',
      uploadImage: 'Upload Image',
      isPartner: 'Mark as Partner',
      save: 'Save Doctor',
      cancel: 'Cancel',
      imageUploadTip: 'Click or drag file to this area to upload',
    },
    userMenu: {
      greeting: 'Hello',
      changeLanguage: 'Change Language',
      arabic: 'العربية',
      english: 'English',
      toggleTheme: 'Toggle Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      pink: 'Pink',
      blue: 'Blue',
      brown: 'Brown',
      emerald: 'Emerald',
      amethyst: 'Amethyst',
      ruby: 'Ruby',
      citrine: 'Citrine',
      lavender: 'Lavender',
      mint: 'Mint',
      ocean: 'Ocean',
      sunset: 'Sunset',
      sandstone: 'Sandstone',
      aiTools: 'AI Tools',
      aiChat: 'AI Chat',
      internetSearch: 'Internet Doctor Search',
      quickAdd: 'Quick Add Doctors',
      dataActions: 'Data Actions',
      searchOnMap: 'Search on Map',
      exportData: 'Backup Data',
      importData: 'Restore Data',
      management: 'Management',
      resetAllReferrals: 'Reset All Referrals',
      uncheckAllPartners: 'Uncheck All Partners',
      deleteAllDoctors: 'Delete All Doctors',
      about: 'About',
    },
    dialogs: {
      confirm: 'Confirm',
      cancel: 'Cancel',
      resetReferralsTitle: 'Are you sure?',
      resetReferralsDesc: 'This will reset the referral count for ALL doctors to 0. This action cannot be undone.',
      uncheckPartnersTitle: 'Are you sure?',
      uncheckPartnersDesc: 'This will remove the partner status from ALL doctors. This action cannot be undone.',
      deleteDoctorTitle: 'Delete Doctor?',
      deleteDoctorDesc: 'Are you sure you want to delete this doctor? This action cannot be undone.',
      deleteAllDoctorsTitle: 'Delete All Doctors?',
      deleteAllDoctorsDesc: 'Are you sure you want to delete ALL doctors from your list? This action is permanent and cannot be undone.',
      aboutTitle: 'About Spirit',
      aboutDesc: 'Crafted with care to streamline your professional life, enabling you to manage your doctor directory with ease and efficiency.',
      contactOwner: 'To inquire or make suggestions, contact the project owner:',
      chatTitle: 'AI Medical Assistant',
      chatPlaceholder: 'Ask a question...',
      chatWelcome: 'Hello! How can I help you today?',
      internetSearchTitle: 'Internet Doctor Search',
      internetSearchDesc: 'Use AI to search for doctors across the internet based on name, specialty, city, etc.',
      internetSearchPlaceholder: 'e.g., "Cardiologist in Baghdad", "Dr. Ali phone number"...',
      internetSearching: 'AI is searching the internet for doctors...',
      addAllResults: 'Add all {count} results',
      noResultsFoundTitle: 'No Results Found',
      noResultsFoundDesc: 'Try a different or more general search query.',
      internetSearchReadyTitle: 'AI is Ready to Search',
      internetSearchReadyDesc: 'Enter a query above to search for doctors across the web.',
    },
    toasts: {
      offline: 'You are now offline. Some features may be unavailable.',
      online: 'You are back online.',
      locationError: 'Could not get location. Please enable location services.',
      exportSuccess: 'Data exported successfully!',
      exportError: 'Failed to export data.',
      importSuccess: 'Data imported successfully!',
      importError: 'Failed to import data from file.',
      exporting: 'Exporting...',
      exportingDesc: 'Please wait while the data is being prepared.',
      searchErrorTitle: 'Search Failed',
      searchErrorDesc: 'The AI search failed. Please try again later.',
      doctorAddedTitle: 'Doctor Added',
      doctorAddedDesc: 'has been added to your local list.',
      allDoctorsAddedTitle: 'All Doctors Added',
      allDoctorsAddedDesc: '{count} doctors have been added to your local list.',
      noDataToExport: 'There is no data to export.',
      translatingTitle: 'Translating doctor cards to Arabic...',
      translationSuccessTitle: 'Translation Complete',
      translationErrorTitle: 'Translation Failed',
      noDoctorsToTranslate: 'No doctors to translate.',
    },
    common: {
      loading: 'Loading...',
      noResults: 'No results found. Try a different search.',
      add: 'Add',
      search: 'Search',
      close: 'Close',
      notAvailable: 'N/A',
      next: 'Next',
      previous: 'Previous',
      finish: 'Finish',
      submit: 'Submit',
      save: 'Save',
      backToMenu: 'Back to Main Menu',
      random: 'Random',
      actions: 'Actions'
    },
     admin: {
      dashboardTitle: 'Admin Dashboard',
      usersTable: 'Registered Users',
      username: 'Username',
      phoneNumber: 'Phone Number',
      role: 'Role',
      actions: 'Actions',
      addUser: 'Add User',
      makeAdmin: 'Make Admin',
      removeAdmin: 'Remove Admin',
      deleteUserTitle: 'Delete User?',
      deleteUserDesc: 'Are you sure you want to delete this user',
      addUserDialogTitle: 'Add New User',
      editUserDialogTitle: 'Edit User',
      saveChanges: 'Save Changes',
      editUserSuccess: 'User updated successfully',
      editUserError: 'Failed to update user. Email or phone may already exist.',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      addUserSuccess: 'User added successfully',
      addUserError: 'Failed to add user',
      deactivateUser: 'Deactivate',
      reactivateUser: 'Reactivate',
      approveUser: 'Approve',
      status: {
        pending: 'Pending',
        active: 'Active',
        deactivated: 'Deactivated',
        all: "All",
        admitted: "Admitted",
        discharged: "Discharged",
        title: "Status",
      },
      pendingDesc: 'Your account is awaiting approval. Please contact the administrator to activate it.',
      contactAdmin: 'Contact: {phoneNumber}',
      bannedDesc: 'Your account has been deactivated by an administrator. Please contact support for more information.',
      approvalSystem: 'Enable User Approval System',
      sessionEndsIn: 'Session ends in:',
      sessionExpiredTitle: 'Session Expired',
      sessionExpiredDesc: 'You have been logged out for security reasons.',
      deactivatesIn: 'Deactivates in {days}d {hours}h',
      stats: {
        vsYesterday: "vs. yesterday",
        weeklyTotal: "Weekly Patients (Last 7 Days)",
        vsLastWeek: "vs. last week",
        busiestDepartment: "Busiest Department (7 Days)",
        with: "with",
        patients: "patients",
        weeklyTraffic: "Weekly Patient Traffic",
        noPatientData: "No patient data available to display charts."
      }
    },
    partnerDashboard: {
      description: 'A quick overview of your partner doctors and their referrals.',
      editReferrals: 'Edit Referrals',
      noPartners: 'You have no partner doctors yet.',
      exportExcel: 'Export to Excel',
      close: 'Close',
      exportFileName: 'Partner_Doctors_Report',
      exportName: 'Doctor Name',
      exportAddress: 'Address',
      exportPhone: 'Phone',
      exportReferrals: 'Referrals',
      exportCommission: 'Commission (USD)',
    },
    referralNotes: {
      title: "Referral Case Notes",
      description: "Notes for cases referred by {name}",
      caseLabel: "Case #{index}",
      save: "Save Notes",
      noCases: "No referrals to show. Increase the referral count to add notes.",
      patientName: "Patient Name",
      referralDate: "Referral Date",
      testDate: "Test Date",
      testType: "Test Type",
      patientAge: "Patient Age",
      chronicDiseases: "Chronic Diseases",
      chronicDiseasesPlaceholder: "e.g., Diabetes, Hypertension",
      manageCases: "Manage Cases",
      addCase: "Add Case",
      removeCase: "Remove Last Case",
      exportExcel: 'Export Cases to Excel',
      noCasesToExport: 'No cases to export.',
    },
    doctorList: {
      name: 'Name',
      specialty: 'Specialty',
      actions: 'Actions',
    },
    welcome: {
      title: "Welcome to Spirit!",
      description: "Your intelligent medical directory. Here are some key features to get you started:",
      feature1: "Build Your Directory: Add, edit, and manage your list of doctors.",
      feature2: "Manage Referrals: Easily track patient referrals and case notes.",
      feature3: "Harness AI Power: Use AI to find new doctors or chat with a medical assistant.",
      feature4: "Secure Your Data: Backup and restore your data anytime.",
      start: "Let's Get Started"
    },
    departments: {
      reception: 'Reception',
      emergency: 'Emergency',
      icu: 'ICU',
      wards: 'Inpatient Wards',
      surgicalOperations: 'Surgical Operations',
      pharmacy: 'Pharmacy',
      laboratories: 'Laboratories',
      radiology: 'Radiology & Ultrasound',
      nursing: 'Nursing',
      internalMedicine: 'Internal Medicine',
      generalSurgery: 'General Surgery',
      obGyn: 'Obstetrics & Gynecology',
      pediatrics: 'Pediatrics',
      orthopedics: 'Orthopedics',
      urology: 'Urology',
      ent: 'ENT',
      ophthalmology: 'Ophthalmology',
      dermatology: 'Dermatology',
      cardiology: 'Cardiology & Chest',
      neurology: 'Neurology',
      oncology: 'Oncology',
      nephrology: 'Nephrology & Dialysis',
      bloodBank: 'Blood Bank',
      accounts: 'Accounts',
      medicalRecords: 'Medical Records',
      sterilization: 'Sterilization',
      services: 'Services',
      representatives: 'Representatives',
      admin: 'Admin',
      medicalSections: 'Medical Departments',
      adminSections: 'Administrative & Service Departments'
    },
    reception: {
      title: 'New Patient Registration',
      editTitle: 'Edit Patient Data',
      description: 'Register a new patient and assign them to a department.',
      editDescription: "Update the patient's information.",
      patientName: 'Patient Name',
      patientNamePlaceholder: 'Enter patient\'s full name',
      dob: 'Date of Birth',
      day: 'Day',
      month: 'Month',
      year: 'Year',
      age: 'Age',
      years: 'years',
      receptionDate: 'Reception Date',
      address: 'Patient Address',
      governorate: 'Governorate',
      governoratePlaceholder: 'Select a governorate',
      region: 'Region/District',
      regionPlaceholder: 'e.g., Karrada',
      mahalla: 'Mahalla',
      zuqaq: 'Zuqaq',
      dar: 'Dar',
      idUpload: 'ID Card Upload',
      idFront: 'Front Side',
      idBack: 'Back Side',
      assignDepartment: 'Assign to Department',
      assignDepartmentPlaceholder: 'Select a department',
      referredBy: 'Referred by Doctor',
      referredByPlaceholder: 'Select referring doctor (optional)',
      addDoctor: 'Add New Doctor',
      addPatient: 'Add Patient',
      submitPatient: 'Register Patient',
      updatePatient: 'Update Patient',
      submitSuccessTitle: 'Patient Registered',
      submitSuccessDesc: '{patientName} has been routed to {department}.',
      updateSuccessTitle: 'Patient Updated',
      updateSuccessDesc: "{patientName}'s data has been updated successfully.",
      noPatientsTitle: 'No Patients Registered Yet',
      noPatientsDesc: 'Click the button to register the first patient.',
      toDepartment: 'to',
      serviceRequired: 'Service Required',
      selectServicePlaceholder: 'Select a service',
      validation: {
        patientNameRequired: 'Patient name is required',
        dayRequired: 'Day is required',
        monthRequired: 'Month is required',
        yearRequired: 'Year is required',
        receptionDateRequired: 'Reception date is required',
        governorateRequired: 'Governorate is required',
        regionRequired: 'Region is required',
        mahallaRequired: 'Mahalla is required',
        zuqaqRequired: 'Zuqaq is required',
        darRequired: 'Dar is required',
        departmentRequired: 'Department selection is required',
      }
    },
    pharmacy: {
      inventory: 'Drug Inventory',
      addDrug: 'Add Drug',
      editDrug: 'Edit Drug',
      drugName: 'Drug Name',
      quantity: 'Quantity',
      quantityAvailable: 'Available',
      price: 'Price',
      searchPlaceholder: 'Search for a drug...',
      iqd: 'IQD',
      salesCart: 'Sales Cart',
      selectPatient: 'Select a patient for this sale',
      cartEmpty: 'Cart is empty. Add drugs from the inventory.',
      total: 'Total',
      confirmSale: 'Confirm Sale',
      selectPatientError: 'Please select a patient first.',
      cartEmptyError: 'The sales cart is empty.',
      saleConfirmed: 'Sale confirmed and added to patient records.',
      notEnoughStock: 'Not enough stock available.'
    },
    surgery: {
      newBooking: 'New Booking',
      editBooking: 'Edit Booking',
      patientName: 'Patient Name',
      surgeryType: 'Surgery Type',
      surgeonName: 'Surgeon Name',
      date: 'Date & Time',
      duration: 'Duration (minutes)',
      cost: 'Cost',
      noBookings: 'No bookings for this day.',
      status: {
        title: 'Status',
        scheduled: 'Scheduled',
        completed: 'Completed',
        canceled: 'Canceled',
      },
    },
    lab: {
      testList: 'Available Tests',
      searchPlaceholder: 'Search for a test...',
      testName: 'Test Name',
      price: 'Price',
      iqd: 'IQD',
      costCalculator: 'Test Order',
      noTestsSelected: 'Add tests from the list to create an order.',
      totalCost: 'Total Cost',
      selectPatient: 'Select a patient for this order',
      confirmOrder: 'Confirm Order',
      selectPatientError: 'Please select a patient first.',
      noTestsSelectedError: 'No tests selected for the order.',
      orderConfirmed: 'Order confirmed and added to patient records.',
      test: 'Test'
    },
    radiology: {
      serviceList: 'Available Procedures',
      searchPlaceholder: 'Search for a procedure...',
      serviceName: 'Procedure Name',
      price: 'Price',
      iqd: 'IQD',
      costCalculator: 'Procedure Order',
      noServicesSelected: 'Add procedures from the list to create an order.',
      totalCost: 'Total Cost',
      selectPatient: 'Select a patient for this order',
      confirmOrder: 'Confirm Order',
      selectPatientError: 'Please select a patient first.',
      noServicesSelectedError: 'No procedures selected for the order.',
      orderConfirmed: 'Order confirmed and added to patient records.',
      procedure: 'Procedure'
    },
    oncology: {
      totalDoctors: 'Total Doctors',
      totalReferrals: 'Total Referrals',
      mostActive: 'Most Active Doctor',
      recentCases: 'Recent Cases',
      noRecentCases: 'No recent cases for this department.',
      doctorList: 'Department Doctors',
      noDoctors: 'No doctors in this department.',
      addFirstDoctor: 'Add a doctor to get started.',
      specializedTests: 'Specialized Oncology Tests & Procedures',
    },
    simulation: {
      start: 'Start Live Simulation',
      stop: 'Stop Live Simulation',
      started: 'Live simulation started!',
      stopped: 'Live simulation stopped.',
      doctorAdded: 'New Doctor Added',
      patientAdded: 'New Patient Registered',
      doctorRemoved: 'Old Doctor Archived',
      patientArchived: 'Old Patient Archived',
      referralUpdate: 'Referral Count Updated',
      labTest: 'Lab Test Ordered',
      pharmacyBill: 'Medication Dispensed',
      paymentMade: 'Patient Payment Received',
      labTestDesc: 'got a lab test.',
      pharmacyBillDesc: 'bought medicine.',
      paymentMadeDesc: '{patientName} paid {amount} IQD.',
      referralUpdateDesc: '{doctorName} now has {count} referrals.',
      patientAdmitted: 'Patient Admitted to Ward',
      patientAdmittedDesc: '{patientName} was admitted to Floor {floor}, Room {room}.',
      dailyCharge: 'Daily Inpatient Charge',
      dailyChargeDesc: 'Daily charge of {amount} IQD added for {patientName}.'
    },
    accounts: {
        patientBalances: "Patient Balances",
        searchPatient: "Search for a patient...",
        balance: "Balance",
        viewDetails: "Details",
        invoiceFor: "Invoice for",
        invoiceDesc: "A detailed list of all financial transactions for this patient.",
        noRecords: "No financial records for this patient yet.",
        totalBalance: "Total Balance",
        addPayment: "Add Payment",
        paymentAmount: "Payment Amount",
        paymentReceived: "Payment Received",
    },
    notifications: {
      title: "Notifications",
      description: "Recent activity from across the hospital.",
      empty: "You have no new notifications.",
      markAllRead: "Mark all as read",
      clearAll: "Clear All"
    },
    emergency: {
      waiting: "Waiting",
      inTreatment: "In Treatment",
      observation: "Observation",
      admitToICU: "Admit to ICU",
      admitToWard: "Admit to Ward",
      discharge: "Discharge",
      triage: {
        critical: "Critical",
        urgent: "Urgent",
        stable: "Stable",
        minor: "Minor"
      },
      vitals: {
        heartRate: "Heart Rate",
        bloodPressure: "Blood Pressure",
        spo2: "SpO2",
        temperature: "Temperature"
      }
    },
    icu: {
      bed: "Bed",
      vacant: "Vacant",
      monitorFor: "Live Monitor for",
    },
    medicalRecords: {
      title: "Medical Records",
      description: "Search and manage the central patient archive.",
      searchPlaceholder: "Search by patient name or ID...",
      fullName: "Full Name",
      age: "Age",
      sex: "Sex",
      firstAdmission: "First Admission",
      lastVisit: "Last Visit",
      noRecords: "No patient records found.",
      viewHistory: "View History",
      patientHistoryFor: "Patient History for",
      exportReports: "Export Reports",
      exportDesc: "Export patient data to Excel.",
      exportDaily: "Export Daily Report",
      exportMonthly: "Export Monthly Report",
      exportPatient: "Export Patient Report",
      selectPatientPlaceholder: "Select a patient to export",
      noDataToExport: "No data found for the selected criteria.",
      status: {
        title: "Status",
        all: "All",
        admitted: "Admitted",
        discharged: "Discharged"
      }
    },
    sterilization: {
      title: "Central Sterilization",
      description: "Monitor the status of instrument sterilization cycles.",
      stage1: "Cleaning & Decontamination",
      stage2: "Packaging",
      stage3: "Sterilization (Autoclave)",
      stage4: "Sterile Storage",
      empty: "No instrument sets in this stage.",
      instrumentSet: "Instrument Set",
      cycle: "Cycle",
      inCycle: "In Cycle",
      cycleComplete: "Sterilization Cycle Complete",
      nowInStorage: "is now in sterile storage."
    },
    services: {
      title: "Hospital Services",
      description: "Manage maintenance, cleaning, and other service requests.",
      newRequest: "New Requests",
      inProgress: "In Progress",
      completed: "Completed",
      requestFrom: "Request from",
      moveToProgress: "Move to In Progress",
      moveToCompleted: "Move to Completed",
      moveToNew: "Return to New"
    },
    wards: {
      title: "Inpatient Wards",
      selectFloor: "Select Floor",
      floor: "Floor",
      room: "Room",
      vacant: "Vacant",
      occupiedBy: "Occupied by",
      patientDetails: "Patient Details",
      admitted: "Admitted",
      attendingDoctor: "Attending Doctor",
      admissionFee: 'Ward Admission Fee',
      directAdmissionTitle: 'Direct Patient Admission',
      directAdmissionDesc: 'Register a new patient directly into room {room}.',
      admitPatient: 'Admit Patient',
      admissionSuccessTitle: 'Patient Admitted',
      admissionSuccessDesc: '{patientName} has been admitted to floor {floor}, room {room}.',
      selectPatientForRoom: 'Select a patient to admit into room {room}.',
      selectPatientPlaceholder: 'Select an available patient',
      noAvailablePatients: 'No patients available for admission.',
    }
  },
  ar: {
    appName: 'روح',
    appSubtitle: 'لادارة المراكز والمستشفيات',
    auth: {
      login: 'تسجيل الدخول',
      signup: 'إنشاء حساب',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      email: 'البريد الإلكتروني',
      phoneNumber: 'رقم الهاتف (اختياري)',
      loginCta: 'سجل الدخول إلى حسابك',
      signupCta: 'إنشاء حساب جديد',
      noAccount: 'ليس لديك حساب؟',
      haveAccount: 'لديك حساب بالفعل؟',
      logout: 'تسجيل الخروج',
      signupSuccessTitle: 'تم إنشاء الحساب',
      signupSuccessDesc: 'تم إنشاء حسابك بنجاح! يمكنك الآن تسجيل الدخول.',
      signupFailedTitle: 'فشل في إنشاء الحساب',
      signupFailedDesc: 'يوجد مستخدم بهذا البريد الإلكتروني أو رقم الهاتف بالفعل.',
    },
    header: {
      searchPlaceholder: 'ابحث بالاسم، التخصص، العنوان...',
      addDoctor: 'إضافة طبيب',
      filterPartners: 'تصفية الشركاء',
      totalDoctors: 'الأطباء',
      totalPartners: 'الشركاء',
      adminDashboard: 'لوحة تحكم المسؤول',
      partnerDashboard: 'لوحة الشركاء',
      gridView: 'عرض شبكي',
      listView: 'عرض قائمة',
      sortBy: 'فرز حسب',
      sort: {
        name: 'الاسم',
        date: 'تاريخ الإضافة',
        address: 'العنوان',
      },
      translateAll: 'ترجمة كل البطاقات',
      enterFullscreen: 'الدخول لوضع ملء الشاشة',
      exitFullscreen: 'الخروج من وضع ملء الشاشة',
    },
    doctorCard: {
      partner: 'شريك',
      referrals: 'الإحالات',
      commission: 'العمولة',
      usd: 'دولار',
      setMyLocation: 'تحديد موقعي',
      call: 'اتصال',
      map: 'خريطة',
      edit: 'تعديل',
      delete: 'حذف',
      availability: 'التواجد',
      days: {
        Sat: 'سبت',
        Sun: 'أحد',
        Mon: 'إثنين',
        Tue: 'ثلاثاء',
        Wed: 'أربعاء',
        Thu: 'خميس',
        Fri: 'جمعة',
      },
      notSet: 'لم يحدد',
      viewCases: 'عرض حالات الإحالة',
    },
    doctorForm: {
      addTitle: 'إضافة طبيب جديد',
      editTitle: 'تعديل بيانات الطبيب',
      name: 'اسم الطبيب',
      specialty: 'التخصص',
      phoneNumber: 'رقم الهاتف',
      clinicAddress: 'عنوان العيادة',
      clinicCardImage: 'صورة بطاقة العيادة',
      uploadImage: 'رفع صورة',
      isPartner: 'تحديد كشريك',
      save: 'حفظ الطبيب',
      cancel: 'إلغاء',
      imageUploadTip: 'انقر أو اسحب الملف إلى هذه المنطقة للتحميل',
    },
    userMenu: {
      greeting: 'أهلاً',
      changeLanguage: 'تغيير اللغة',
      arabic: 'العربية',
      english: 'English',
      toggleTheme: 'تغيير المظهر',
      light: 'فاتح',
      dark: 'داكن',
      system: 'النظام',
      pink: 'وردي',
      blue: 'أزرق',
      brown: 'بني',
      emerald: 'زمردي',
      amethyst: 'جمشتي',
      ruby: 'ياقوتي',
      citrine: 'كهرماني',
      lavender: 'خزامى',
      mint: 'نعناع',
      ocean: 'محيط',
      sunset: 'غروب',
      sandstone: 'حجر رملي',
      aiTools: 'أدوات الذكاء الاصطناعي',
      aiChat: 'محادثة AI',
      internetSearch: 'بحث في الإنترنت عن أطباء',
      quickAdd: 'إضافة أطباء بسرعة',
      dataActions: 'إجراءات البيانات',
      searchOnMap: 'بحث على الخريطة',
      exportData: 'نسخ احتياطي للبيانات',
      importData: 'استعادة البيانات',
      management: 'إدارة',
      resetAllReferrals: 'إعادة تعيين كل الإحالات',
      uncheckAllPartners: 'إلغاء تحديد كل الشركاء',
      deleteAllDoctors: 'حذف جميع الأطباء',
      about: 'حول التطبيق',
    },
    dialogs: {
      confirm: 'تأكيد',
      cancel: 'إلغاء',
      resetReferralsTitle: 'هل أنت متأكد؟',
      resetReferralsDesc: 'سيؤدي هذا إلى إعادة تعيين عدد الإحالات لجميع الأطباء إلى 0. لا يمكن التراجع عن هذا الإجراء.',
      uncheckPartnersTitle: 'هل أنت متأكد؟',
      uncheckPartnersDesc: 'سيؤدي هذا إلى إزالة حالة الشريك من جميع الأطباء. لا يمكن التراجع عن هذا الإجراء.',
      deleteDoctorTitle: 'حذف الطبيب؟',
      deleteDoctorDesc: 'هل أنت متأكد من أنك تريد حذف هذا الطبيب؟ لا يمكن التراجع عن هذا الإجراء.',
      deleteAllDoctorsTitle: 'حذف جميع الأطباء؟',
      deleteAllDoctorsDesc: 'هل أنت متأكد من رغبتك في حذف جميع الأطباء من قائمتك؟ هذا الإجراء دائم ولا يمكن التراجع عنه.',
      aboutTitle: 'عن روح',
      aboutDesc: 'صُنع بعناية لتبسيط حياتك المهنية، مما يتيح لك إدارة دليل الأطباء الخاص بك بسهولة وكفاءة.',
      contactOwner: 'للاستفسار أو تقديم اقتراحات، تواصل مع صاحب المشروع:',
      chatTitle: 'مساعد طبي بالذكاء الاصطناعي',
      chatPlaceholder: 'اطرح سؤالاً...',
      chatWelcome: 'أهلاً بك! كيف يمكنني مساعدتك اليوم؟',
      internetSearchTitle: 'بحث في الإنترنت عن أطباء',
      internetSearchDesc: 'استخدم الذكاء الاصطناعي للبحث عن أطباء عبر الإنترنت بناءً على الاسم، التخصص، المدينة، إلخ.',
      internetSearchPlaceholder: 'مثال: "طبيب قلب في بغداد"، "رقم هاتف دكتور علي"...',
      internetSearching: 'يقوم الذكاء الاصطناعي بالبحث في الإنترنت عن الأطباء...',
      addAllResults: 'إضافة كل النتائج ({count})',
      noResultsFoundTitle: 'لم يتم العثور على نتائج',
      noResultsFoundDesc: 'حاول استخدام كلمات بحث مختلفة أو أكثر عمومية.',
      internetSearchReadyTitle: 'الذكاء الاصطناعي جاهز للبحث',
      internetSearchReadyDesc: 'أدخل استعلامًا أعلاه للبحث عن الأطباء عبر الويب.',
    },
    toasts: {
      offline: 'أنت غير متصل بالإنترنت. بعض الميزات قد لا تكون متاحة.',
      online: 'لقد عدت متصلاً بالإنترنت.',
      locationError: 'تعذر الحصول على الموقع. يرجى تفعيل خدمات الموقع.',
      exportSuccess: 'تم تصدير البيانات بنجاح!',
      exportError: 'فشل تصدير البيانات.',
      importSuccess: 'تم استيراد البيانات بنجاح!',
      importError: 'فشل استيراد البيانات من الملف.',
      exporting: 'جاري التصدير...',
      exportingDesc: 'يرجى الانتظار بينما يتم تجهيز البيانات.',
      searchErrorTitle: 'فشل البحث',
      searchErrorDesc: 'فشل بحث الذكاء الاصطناعي. يرجى المحاولة مرة أخرى لاحقًا.',
      doctorAddedTitle: 'تمت إضافة الطبيب',
      doctorAddedDesc: 'تمت إضافته إلى قائمتك المحلية.',
      allDoctorsAddedTitle: 'تمت إضافة جميع الأطباء',
      allDoctorsAddedDesc: 'تمت إضافة {count} أطباء إلى قائمتك المحلية.',
      noDataToExport: 'لا توجد بيانات لتصديرها.',
      translatingTitle: 'جاري ترجمة بطاقات الأطباء إلى العربية...',
      translationSuccessTitle: 'اكتملت الترجمة',
      translationErrorTitle: 'فشلت الترجمة',
      noDoctorsToTranslate: 'لا يوجد أطباء لترجمتهم.',
    },
    common: {
      loading: 'جار التحميل...',
      noResults: 'لم يتم العثور على نتائج. حاول البحث بكلمات مختلفة.',
      add: 'إضافة',
      search: 'بحث',
      close: 'إغلاق',
      notAvailable: 'غير متوفر',
      next: 'التالي',
      previous: 'السابق',
      finish: 'إنهاء',
      submit: 'إرسال',
      save: 'حفظ',
      backToMenu: 'العودة للقائمة الرئيسية',
      random: 'عشوائي',
      actions: 'إجراءات',
    },
    admin: {
      dashboardTitle: 'لوحة تحكم المسؤول',
      usersTable: 'المستخدمون المسجلون',
      username: 'اسم المستخدم',
      phoneNumber: 'رقم الهاتف',
      role: 'الدور',
      actions: 'الإجراءات',
      addUser: 'إضافة مستخدم',
      makeAdmin: 'جعله مسؤولاً',
      removeAdmin: 'إزالة المسؤول',
      deleteUserTitle: 'حذف المستخدم؟',
      deleteUserDesc: 'هل أنت متأكد أنك تريد حذف هذا المستخدم',
      addUserDialogTitle: 'إضافة مستخدم جديد',
      editUserDialogTitle: 'تعديل مستخدم',
      saveChanges: 'حفظ التغييرات',
      editUserSuccess: 'تم تحديث المستخدم بنجاح',
      editUserError: 'فشل تحديث المستخدم. قد يكون البريد الإلكتروني أو رقم الهاتف موجوداً بالفعل.',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      addUserSuccess: 'تمت إضافة المستخدم بنجاح',
      addUserError: 'فشل في إضافة المستخدم',
      deactivateUser: 'إيقاف التنشيط',
      reactivateUser: 'إعادة التنشيط',
      approveUser: 'موافقة',
      status: {
        pending: 'في انتظار المراجعة',
        active: 'نشط',
        deactivated: 'غير نشط',
        all: "الكل",
        admitted: "راقد",
        discharged: "مُخرَّج",
        title: "الحالة",
      },
      pendingDesc: 'حسابك في انتظار الموافقة. يرجى التواصل مع المسؤول لتفعيل حسابك.',
      contactAdmin: 'للتواصل: {phoneNumber}',
      bannedDesc: 'تم إيقاف تنشيط حسابك من قبل المسؤول. يرجى التواصل مع الدعم لمزيد من المعلومات.',
      approvalSystem: 'تفعيل نظام الموافقة على المستخدمين',
      sessionEndsIn: 'تنتهي الجلسة خلال:',
      sessionExpiredTitle: 'انتهت صلاحية الجلسة',
      sessionExpiredDesc: 'تم تسجيل خروجك لأسباب أمنية.',
      deactivatesIn: 'ينتهي التفعيل خلال {days} يوم و {hours} ساعة',
      stats: {
        vsYesterday: "مقارنة بالأمس",
        weeklyTotal: "مرضى الأسبوع (آخر 7 أيام)",
        vsLastWeek: "مقارنة بالأسبوع الماضي",
        busiestDepartment: "القسم الأكثر ازدحاماً (7 أيام)",
        with: "بواقع",
        patients: "مريض",
        weeklyTraffic: "حركة المرضى الأسبوعية",
        noPatientData: "لا توجد بيانات مرضى لعرض الرسوم البيانية."
      }
    },
    partnerDashboard: {
      description: 'نظرة سريعة على الأطباء الشركاء وإحالاتهم.',
      editReferrals: 'تعديل الإحالات',
      noPartners: 'ليس لديك أطباء شركاء بعد.',
      exportExcel: 'تصدير Excel',
      close: 'إغلاق',
      exportFileName: 'تقرير_الأطباء_الشركاء',
      exportName: 'اسم الطبيب',
      exportAddress: 'العنوان',
      exportPhone: 'الهاتف',
      exportReferrals: 'الإحالات',
      exportCommission: 'العمولة (دولار)',
    },
    referralNotes: {
      title: "ملاحظات حالات الإحالة",
      description: "ملاحظات للحالات المحالة من الدكتور {name}",
      caseLabel: "الحالة رقم {index}",
      save: "حفظ الملاحظات",
      noCases: "لا توجد إحالات لعرضها. قم بزيادة عدد الإحالات لإضافة ملاحظات.",
      patientName: "اسم المريض",
      referralDate: "تاريخ التحويل",
      testDate: "تاريخ الفحص",
      testType: "نوع الفحص",
      patientAge: "عمر المريض",
      chronicDiseases: "الأمراض المزمنة",
      chronicDiseasesPlaceholder: "مثال: سكري، ضغط الدم",
      manageCases: "إدارة الحالات",
      addCase: "إضافة حالة",
      removeCase: "حذف آخر حالة",
      exportExcel: 'تصدير الحالات إلى Excel',
      noCasesToExport: 'لا توجد حالات لتصديرها.',
    },
    doctorList: {
      name: 'الاسم',
      specialty: 'التخصص',
      actions: 'Actions',
    },
    welcome: {
      title: "أهلاً بك في روح!",
      description: "دليلك الطبي الذكي. إليك بعض الميزات الرئيسية لتبدأ:",
      feature1: "ابنِ دليلك: أضف وحرر وأدر قائمة الأطباء الخاصة بك.",
      feature2: "أدر الإحالات: تتبع إحالات المرضى وملاحظات الحالات بسهولة.",
      feature3: "استخدم قوة الذكاء الاصطناعي: ابحث عن أطباء جدد أو تحدث مع مساعد طبي ذكي.",
      feature4: "أمّن بياناتك: قم بعمل نسخة احتياطية واستعادة لبياناتك في أي وقت.",
      start: "لنبدأ الآن"
    },
    departments: {
      reception: 'الاستعلامات',
      emergency: 'الطوارئ',
      icu: 'العناية المركزة',
      wards: 'غرف الرقود',
      surgicalOperations: 'العمليات الجراحية',
      pharmacy: 'الصيدلية',
      laboratories: 'المختبرات',
      radiology: 'الأشعة والسونار',
      nursing: 'التمريض',
      internalMedicine: 'الباطنية',
      generalSurgery: 'الجراحة العامة',
      obGyn: 'النسائية والتوليد',
      pediatrics: 'الأطفال',
      orthopedics: 'العظام والكسور',
      urology: 'المسالك البولية',
      ent: 'الأنف والأذن والحنجرة',
      ophthalmology: 'العيون',
      dermatology: 'الجلدية',
      cardiology: 'القلب والصدر',
      neurology: 'الأعصاب',
      oncology: 'الأورام',
      nephrology: 'الكلى والغسيل الكلوي',
      bloodBank: 'مصرف الدم',
      accounts: 'الحسابات',
      medicalRecords: 'السجلات الطبية',
      sterilization: 'التعقيم',
      services: 'الخدمات',
      representatives: 'المندوبين',
      admin: 'الإدارة',
      medicalSections: 'الأقسام الطبية',
      adminSections: 'الأقسام الإدارية والخدمية'
    },
    reception: {
      title: 'تسجيل مريض جديد',
      editTitle: 'تعديل بيانات المريض',
      description: 'تسجيل مريض جديد وتوجيهه إلى القسم المناسب.',
      editDescription: "تحديث معلومات المريض.",
      patientName: 'اسم المريض',
      patientNamePlaceholder: 'أدخل الاسم الكامل للمريض',
      dob: 'تاريخ الميلاد',
      day: 'يوم',
      month: 'شهر',
      year: 'سنة',
      age: 'العمر',
      years: 'سنوات',
      receptionDate: 'تاريخ الاستقبال',
      address: 'عنوان المريض',
      governorate: 'المحافظة',
      governoratePlaceholder: 'اختر محافظة',
      region: 'المنطقة / القضاء',
      regionPlaceholder: 'مثال: الكرادة',
      mahalla: 'محلة',
      zuqaq: 'زقاق',
      dar: 'دار',
      idUpload: 'رفع بطاقة الهوية',
      idFront: 'الوجه الأمامي',
      idBack: 'الوجه الخلفي',
      assignDepartment: 'تحويل إلى قسم',
      assignDepartmentPlaceholder: 'اختر قسماً',
      referredBy: 'محال من طبيب',
      referredByPlaceholder: 'اختر الطبيب المُحيل (اختياري)',
      addDoctor: 'إضافة طبيب جديد',
      addPatient: 'إضافة مريض',
      submitPatient: 'تسجيل المريض',
      updatePatient: 'تحديث المريض',
      submitSuccessTitle: 'تم تسجيل المريض',
      submitSuccessDesc: 'تم تحويل {patientName} إلى قسم {department}.',
      updateSuccessTitle: 'تم تحديث المريض',
      updateSuccessDesc: "تم تحديث بيانات {patientName} بنجاح.",
      noPatientsTitle: 'لا يوجد مرضى مسجلون بعد',
      noPatientsDesc: 'انقر على الزر لبدء تسجيل أول مريض.',
      toDepartment: 'إلى قسم',
      serviceRequired: 'الخدمة المطلوبة',
      selectServicePlaceholder: 'اختر خدمة',
      validation: {
        patientNameRequired: 'اسم المريض مطلوب',
        dayRequired: 'اليوم مطلوب',
        monthRequired: 'الشهر مطلوب',
        yearRequired: 'السنة مطلوبة',
        receptionDateRequired: 'تاريخ الاستقبال مطلوب',
        governorateRequired: 'المحافظة مطلوبة',
        regionRequired: 'المنطقة مطلوبة',
        mahallaRequired: 'المحلة مطلوبة',
        zuqaqRequired: 'الزقاق مطلوب',
        darRequired: 'رقم الدار مطلوب',
        departmentRequired: 'يجب اختيار قسم',
      }
    },
    pharmacy: {
      inventory: 'مخزون الأدوية',
      addDrug: 'إضافة دواء',
      editDrug: 'تعديل الدواء',
      drugName: 'اسم الدواء',
      quantity: 'الكمية',
      quantityAvailable: 'المتوفر',
      price: 'السعر',
      searchPlaceholder: 'ابحث عن دواء...',
      iqd: 'دينار',
      salesCart: 'سلة المبيعات',
      selectPatient: 'اختر مريضاً لهذه العملية',
      cartEmpty: 'السلة فارغة. أضف أدوية من المخزون.',
      total: 'الإجمالي',
      confirmSale: 'تأكيد البيع',
      selectPatientError: 'يرجى اختيار مريض أولاً.',
      cartEmptyError: 'سلة المبيعات فارغة.',
      saleConfirmed: 'تم تأكيد البيع وإضافته لسجلات المريض.',
      notEnoughStock: 'الكمية المطلوبة غير متوفرة في المخزون.'
    },
    surgery: {
      newBooking: 'حجز جديد',
      editBooking: 'تعديل الحجز',
      patientName: 'اسم المريض',
      surgeryType: 'نوع العملية',
      surgeonName: 'اسم الجراح',
      date: 'التاريخ والوقت',
      duration: 'المدة (دقائق)',
      cost: 'التكلفة',
      noBookings: 'لا توجد حجوزات لهذا اليوم.',
      status: {
        title: 'الحالة',
        scheduled: 'مجدولة',
        completed: 'مكتملة',
        canceled: 'ملغاة',
      },
    },
    lab: {
      testList: 'الفحوصات المتاحة',
      searchPlaceholder: 'ابحث عن فحص...',
      testName: 'اسم الفحص',
      price: 'السعر',
      iqd: 'دينار',
      costCalculator: 'طلب فحوصات',
      noTestsSelected: 'أضف فحوصات من القائمة لإنشاء طلب.',
      totalCost: 'التكلفة الإجمالية',
      selectPatient: 'اختر مريضاً لهذا الطلب',
      confirmOrder: 'تأكيد الطلب',
      selectPatientError: 'يرجى اختيار مريض أولاً.',
      noTestsSelectedError: 'لم يتم اختيار أي فحوصات للطلب.',
      orderConfirmed: 'تم تأكيد الطلب وإضافته لسجلات المريض.',
      test: 'فحص'
    },
    radiology: {
      serviceList: 'الفحوصات المتاحة',
      searchPlaceholder: 'ابحث عن فحص...',
      serviceName: 'اسم الفحص',
      price: 'السعر',
      iqd: 'دينار',
      costCalculator: 'طلب فحص',
      noServicesSelected: 'أضف فحوصات من القائمة لإنشاء طلب.',
      totalCost: 'التكلفة الإجمالية',
      selectPatient: 'اختر مريضاً لهذا الطلب',
      confirmOrder: 'تأكيد الطلب',
      selectPatientError: 'يرجى اختيار مريض أولاً.',
      noServicesSelectedError: 'لم يتم اختيار أي فحوصات للطلب.',
      orderConfirmed: 'تم تأكيد الطلب وإضافته لسجلات المريض.',
      procedure: 'فحص'
    },
    oncology: {
      totalDoctors: 'إجمالي الأطباء',
      totalReferrals: 'إجمالي الإحالات',
      mostActive: 'الطبيب الأكثر نشاطًا',
      recentCases: 'أحدث الحالات',
      noRecentCases: 'لا توجد حالات حديثة في هذا القسم.',
      doctorList: 'أطباء القسم',
      noDoctors: 'لا يوجد أطباء في هذا القسم.',
      addFirstDoctor: 'أضف طبيباً للبدء.',
      specializedTests: 'فحوصات وعلاجات الأورام المتخصصة',
    },
    simulation: {
      start: 'بدء المحاكاة الحية',
      stop: 'إيقاف المحاكاة الحية',
      started: 'بدأت المحاكاة الحية!',
      stopped: 'توقفت المحاكاة الحية.',
      doctorAdded: 'تمت إضافة طبيب جديد',
      patientAdded: 'تم تسجيل مريض جديد',
      doctorRemoved: 'تمت أرشفة طبيب قديم',
      patientArchived: 'تمت أرشفة مريض قديم',
      referralUpdate: 'تم تحديث عدد الإحالات',
      labTest: 'تم طلب فحص مخبري',
      pharmacyBill: 'تم صرف دواء',
      paymentMade: 'تم استلام دفعة من المريض',
      labTestDesc: 'طلب فحص مخبري',
      pharmacyBillDesc: 'اشترى دواء',
      paymentMadeDesc: '{patientName} دفع مبلغ {amount} دينار.',
      referralUpdateDesc: '{doctorName} لديه الآن {count} إحالات.',
      patientAdmitted: 'تم إدخال مريض إلى الردهة',
      patientAdmittedDesc: 'تم إدخال {patientName} إلى الطابق {floor}، غرفة {room}.',
      dailyCharge: 'تكلفة الإقامة اليومية',
      dailyChargeDesc: 'تمت إضافة تكلفة يومية بقيمة {amount} دينار للمريض {patientName}.'
    },
    accounts: {
        patientBalances: "أرصدة المرضى",
        searchPatient: "ابحث عن مريض...",
        balance: "الرصيد",
        viewDetails: "تفاصيل",
        invoiceFor: "فاتورة المريض",
        invoiceDesc: "قائمة مفصلة بجميع المعاملات المالية لهذا المريض.",
        noRecords: "لا توجد سجلات مالية لهذا المريض بعد.",
        totalBalance: "الرصيد الإجمالي",
        addPayment: "إضافة دفعة",
        paymentAmount: "مبلغ الدفعة",
        paymentReceived: "دفعة مستلمة",
    },
    notifications: {
      title: "الإشعارات",
      description: "آخر الأنشطة من جميع أنحاء المستشفى.",
      empty: "ليس لديك إشعارات جديدة.",
      markAllRead: "تحديد الكل كمقروء",
      clearAll: "مسح الكل"
    },
    emergency: {
      waiting: "في الانتظار",
      inTreatment: "تحت العلاج",
      observation: "تحت الملاحظة",
      admitToICU: "إدخال للعناية المركزة",
      admitToWard: "إدخال للردهة",
      discharge: "تخريج",
      triage: {
        critical: "حرجة",
        urgent: "عاجلة",
        stable: "مستقرة",
        minor: "بسيطة"
      },
      vitals: {
        heartRate: "النبض",
        bloodPressure: "الضغط",
        spo2: "الأكسجين",
        temperature: "الحرارة"
      }
    },
     icu: {
      bed: "سرير",
      vacant: "شاغر",
      monitorFor: "مراقبة حية للمريض",
    },
    medicalRecords: {
      title: "السجلات الطبية",
      description: "ابحث وأدر الأرشيف المركزي للمرضى.",
      searchPlaceholder: "ابحث بالاسم، الرقم التعريفي، أو رقم الهاتف...",
      fullName: "الاسم الكامل",
      age: "العمر",
      sex: "الجنس",
      firstAdmission: "أول دخول",
      lastVisit: "آخر زيارة",
      noRecords: "لا توجد سجلات مرضى.",
      viewHistory: "عرض السجل",
      patientHistoryFor: "السجل المرضي للمريض",
      exportReports: "تصدير التقارير",
      exportDesc: "تصدير بيانات المرضى إلى ملف إكسل.",
      exportDaily: "تصدير تقرير يومي",
      exportMonthly: "تصدير تقرير شهري",
      exportPatient: "تصدير تقرير مريض",
      selectPatientPlaceholder: "اختر مريضاً للتصدير",
      noDataToExport: "لا توجد بيانات للمعايير المحددة."
    },
    sterilization: {
      title: "وحدة التعقيم المركزية",
      description: "مراقبة حالة دورات تعقيم الأدوات.",
      stage1: "التنظيف والتطهير",
      stage2: "التغليف",
      stage3: "التعقيم (الأوتوكليف)",
      stage4: "التخزين المعقم",
      empty: "لا توجد مجموعات أدوات في هذه المرحلة.",
      instrumentSet: "مجموعة أدوات",
      cycle: "دورة",
      inCycle: "في الدورة",
      cycleComplete: "اكتملت دورة التعقيم",
      nowInStorage: "أصبحت الآن في المخزن المعقم."
    },
    services: {
      title: "الخدمات المساندة",
      description: "إدارة طلبات الصيانة، النظافة، والخدمات الأخرى.",
      newRequest: "طلبات جديدة",
      inProgress: "قيد التنفيذ",
      completed: "مكتملة",
      requestFrom: "طلب من",
      moveToProgress: "نقل إلى قيد التنفيذ",
      moveToCompleted: "نقل إلى مكتملة",
      moveToNew: "إرجاع إلى جديد"
    },
    wards: {
      title: "ردهات الرقود",
      selectFloor: "اختر الطابق",
      floor: "الطابق",
      room: "غرفة",
      vacant: "شاغرة",
      occupiedBy: "مشغولة بواسطة",
      patientDetails: "تفاصيل المريض",
      admitted: "تاريخ الدخول",
      attendingDoctor: "الطبيب المشرف",
      admissionFee: 'رسوم دخول الردهة',
      directAdmissionTitle: 'إدخال مباشر للمريض',
      directAdmissionDesc: 'تسجيل مريض جديد مباشرة في الغرفة رقم {room}.',
      admitPatient: 'إدخال المريض',
      admissionSuccessTitle: 'تم إدخال المريض',
      admissionSuccessDesc: 'تم إدخال {patientName} إلى الطابق {floor}، غرفة رقم {room}.',
      selectPatientForRoom: 'اختر مريضًا لإدخاله إلى الغرفة رقم {room}.',
      selectPatientPlaceholder: 'اختر مريضاً متاحاً',
      noAvailablePatients: 'لا يوجد مرضى متاحون للإدخال.',
    }
  },
};
