import type { Translations } from '@/types';

export const translations: Translations = {
  en: {
    appName: 'Spirit',
    appSubtitle: 'For Managing Centers and Hospitals',
    auth: {
      login: 'Login',
      signup: 'Sign Up',
      username: 'Username',
      password: 'Password',
      email: 'Email',
      phoneNumber: 'Phone Number (Optional)',
      loginCta: 'Log into your account',
      signupCta: 'Create a new account',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      logout: 'Logout',
      signupSuccessTitle: 'Account Created',
      signupSuccessDesc: 'You can now log in.',
      signupFailedTitle: 'Signup Failed',
      signupFailedDesc: 'A user with this email or phone number already exists.',
    },
    header: {
      searchPlaceholder: 'Search by name, specialty, address...',
      addDoctor: 'Add Doctor',
      filterPartners: 'Filter Partners',
      totalDoctors: 'Doctors',
      totalPartners: 'Partners',
      adminDashboard: 'Admin Dashboard',
      partnerDashboard: 'Partner Dashboard',
      gridView: 'Grid View',
      listView: 'List View',
      sortBy: 'Sort by',
      sort: {
        name: 'Name',
        date: 'Date Added',
        address: 'Address',
      },
      translateAll: 'Translate All Cards',
      enterFullscreen: 'Enter Fullscreen',
      exitFullscreen: 'Exit Fullscreen',
    },
    doctorCard: {
      partner: 'Partner',
      referrals: 'Referrals',
      commission: 'Commission',
      usd: 'USD',
      setMyLocation: 'Set My Location',
      call: 'Call',
      map: 'Map',
      edit: 'Edit',
      delete: 'Delete',
      availability: 'Availability',
      days: {
        Sat: 'Sat',
        Sun: 'Sun',
        Mon: 'Mon',
        Tue: 'Tue',
        Wed: 'Wed',
        Thu: 'Thu',
        Fri: 'Fri',
      },
      notSet: 'Not Set',
      viewCases: 'View Referral Cases',
    },
    doctorForm: {
      addTitle: 'Add New Doctor',
      editTitle: 'Edit Doctor Details',
      name: 'Doctor Name',
      specialty: 'Specialty',
      phoneNumber: 'Phone Number',
      clinicAddress: 'Clinic Address',
      clinicCardImage: 'Clinic Card Image',
      uploadImage: 'Upload Image',
      isPartner: 'Mark as Partner',
      save: 'Save Doctor',
      cancel: 'Cancel',
      imageUploadTip: 'Click or drag file to this area to upload',
    },
    userMenu: {
      greeting: 'Hello',
      changeLanguage: 'Change Language',
      arabic: 'العربية',
      english: 'English',
      toggleTheme: 'Toggle Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      aiTools: 'AI Tools',
      aiChat: 'AI Chat',
      internetSearch: 'Internet Doctor Search',
      quickAdd: 'Quick Add Doctors',
      dataActions: 'Data Actions',
      searchOnMap: 'Search on Map',
      exportData: 'Export Data File',
      importData: 'Import Data File',
      management: 'Management',
      resetAllReferrals: 'Reset All Referrals',
      uncheckAllPartners: 'Uncheck All Partners',
      about: 'About',
    },
    dialogs: {
      confirm: 'Confirm',
      cancel: 'Cancel',
      resetReferralsTitle: 'Are you sure?',
      resetReferralsDesc: 'This will reset the referral count for ALL doctors to 0. This action cannot be undone.',
      uncheckPartnersTitle: 'Are you sure?',
      uncheckPartnersDesc: 'This will remove the partner status from ALL doctors. This action cannot be undone.',
      deleteDoctorTitle: 'Delete Doctor?',
      deleteDoctorDesc: 'Are you sure you want to delete this doctor? This action cannot be undone.',
      aboutTitle: 'About Spirit',
      aboutDesc: 'Crafted with care to streamline your professional life, enabling you to manage your doctor directory with ease and efficiency.',
      contactOwner: 'To inquire or make suggestions, contact the project owner:',
      chatTitle: 'AI Medical Assistant',
      chatPlaceholder: 'Ask a question...',
      chatWelcome: 'Hello! How can I help you today?',
      internetSearchTitle: 'Internet Doctor Search',
      internetSearchDesc: 'Use AI to search for doctors across the internet based on name, specialty, city, etc.',
      internetSearchPlaceholder: 'e.g., "Cardiologist in Baghdad", "Dr. Ali phone number"...',
      internetSearching: 'AI is searching the internet for doctors...',
      addAllResults: 'Add all {count} results',
    },
    toasts: {
      offline: 'You are now offline. Some features may be unavailable.',
      online: 'You are back online.',
      locationError: 'Could not get location. Please enable location services.',
      exportSuccess: 'Data exported successfully!',
      exportError: 'Failed to export data.',
      importSuccess: 'Data imported successfully!',
      importError: 'Failed to import data from file.',
      exporting: 'Exporting...',
      exportingDesc: 'Please wait while the data is being prepared.',
      searchErrorTitle: 'Search Failed',
      searchErrorDesc: 'The AI search failed. Please try again later.',
      doctorAddedTitle: 'Doctor Added',
      doctorAddedDesc: 'has been added to your local list.',
      allDoctorsAddedTitle: 'All Doctors Added',
      allDoctorsAddedDesc: '{count} doctors have been added to your local list.',
      noDataToExport: 'There is no data to export.',
    },
    common: {
      loading: 'Loading...',
      noResults: 'No results found. Try a different search.',
      add: 'Add',
      search: 'Search',
      close: 'Close',
    },
     admin: {
      dashboardTitle: 'Admin Dashboard',
      usersTable: 'Registered Users',
      username: 'Username',
      phoneNumber: 'Phone Number',
      role: 'Role',
      actions: 'Actions',
      addUser: 'Add User',
      makeAdmin: 'Make Admin',
      removeAdmin: 'Remove Admin',
      deleteUserTitle: 'Delete User?',
      deleteUserDesc: 'Are you sure you want to delete this user',
      addUserDialogTitle: 'Add New User',
      editUserDialogTitle: 'Edit User',
      saveChanges: 'Save Changes',
      editUserSuccess: 'User updated successfully',
      editUserError: 'Failed to update user. Email or phone may already exist.',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      addUserSuccess: 'User added successfully',
      addUserError: 'Failed to add user',
    },
    partnerDashboard: {
      description: 'A quick overview of your partner doctors and their referrals.',
      editReferrals: 'Edit Referrals',
      noPartners: 'You have no partner doctors yet.',
      exportExcel: 'Export to Excel',
      close: 'Close',
    },
    referralNotes: {
      title: "Referral Case Notes",
      description: "Notes for cases referred by {name}",
      caseLabel: "Case #{index}",
      save: "Save Notes",
      noCases: "No referrals to show. Increase the referral count to add notes.",
      patientName: "Patient Name",
      referralDate: "Referral Date",
      testType: "Test Type",
      patientAge: "Patient Age",
      chronicDiseases: "Chronic Diseases",
      chronicDiseasesPlaceholder: "e.g., Diabetes, Hypertension",
      manageCases: "Manage Cases",
      addCase: "Add Case",
      removeCase: "Remove Last Case",
    },
    doctorList: {
      name: 'Name',
      specialty: 'Specialty',
      actions: 'Actions',
    }
  },
  ar: {
    appName: 'روح',
    appSubtitle: 'لادارة المراكز والمستشفيات',
    auth: {
      login: 'تسجيل الدخول',
      signup: 'إنشاء حساب',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      email: 'البريد الإلكتروني',
      phoneNumber: 'رقم الهاتف (اختياري)',
      loginCta: 'سجل الدخول إلى حسابك',
      signupCta: 'إنشاء حساب جديد',
      noAccount: 'ليس لديك حساب؟',
      haveAccount: 'لديك حساب بالفعل؟',
      logout: 'تسجيل الخروج',
      signupSuccessTitle: 'تم إنشاء الحساب',
      signupSuccessDesc: 'يمكنك الآن تسجيل الدخول.',
      signupFailedTitle: 'فشل في إنشاء الحساب',
      signupFailedDesc: 'يوجد مستخدم بهذا البريد الإلكتروني أو رقم الهاتف بالفعل.',
    },
    header: {
      searchPlaceholder: 'ابحث بالاسم، التخصص، العنوان...',
      addDoctor: 'إضافة طبيب',
      filterPartners: 'تصفية الشركاء',
      totalDoctors: 'الأطباء',
      totalPartners: 'الشركاء',
      adminDashboard: 'لوحة تحكم المسؤول',
      partnerDashboard: 'لوحة الشركاء',
      gridView: 'عرض شبكي',
      listView: 'عرض قائمة',
      sortBy: 'فرز حسب',
      sort: {
        name: 'الاسم',
        date: 'تاريخ الإضافة',
        address: 'العنوان',
      },
      translateAll: 'ترجمة كل البطاقات',
      enterFullscreen: 'الدخول لوضع ملء الشاشة',
      exitFullscreen: 'الخروج من وضع ملء الشاشة',
    },
    doctorCard: {
      partner: 'شريك',
      referrals: 'الإحالات',
      commission: 'العمولة',
      usd: 'دولار',
      setMyLocation: 'تحديد موقعي',
      call: 'اتصال',
      map: 'خريطة',
      edit: 'تعديل',
      delete: 'حذف',
      availability: 'التواجد',
      days: {
        Sat: 'سبت',
        Sun: 'أحد',
        Mon: 'إثنين',
        Tue: 'ثلاثاء',
        Wed: 'أربعاء',
        Thu: 'خميس',
        Fri: 'جمعة',
      },
      notSet: 'لم يحدد',
      viewCases: 'عرض حالات الإحالة',
    },
    doctorForm: {
      addTitle: 'إضافة طبيب جديد',
      editTitle: 'تعديل بيانات الطبيب',
      name: 'اسم الطبيب',
      specialty: 'التخصص',
      phoneNumber: 'رقم الهاتف',
      clinicAddress: 'عنوان العيادة',
      clinicCardImage: 'صورة بطاقة العيادة',
      uploadImage: 'رفع صورة',
      isPartner: 'تحديد كشريك',
      save: 'حفظ الطبيب',
      cancel: 'إلغاء',
      imageUploadTip: 'انقر أو اسحب الملف إلى هذه المنطقة للتحميل',
    },
    userMenu: {
      greeting: 'أهلاً',
      changeLanguage: 'تغيير اللغة',
      arabic: 'العربية',
      english: 'English',
      toggleTheme: 'تغيير المظهر',
      light: 'فاتح',
      dark: 'داكن',
      system: 'النظام',
      aiTools: 'أدوات الذكاء الاصطناعي',
      aiChat: 'محادثة AI',
      internetSearch: 'بحث في الإنترنت عن أطباء',
      quickAdd: 'إضافة أطباء بسرعة',
      dataActions: 'إجراءات البيانات',
      searchOnMap: 'بحث على الخريطة',
      exportData: 'تصدير ملف البيانات',
      importData: 'استيراد ملف البيانات',
      management: 'إدارة',
      resetAllReferrals: 'إعادة تعيين كل الإحالات',
      uncheckAllPartners: 'إلغاء تحديد كل الشركاء',
      about: 'حول التطبيق',
    },
    dialogs: {
      confirm: 'تأكيد',
      cancel: 'إلغاء',
      resetReferralsTitle: 'هل أنت متأكد؟',
      resetReferralsDesc: 'سيؤدي هذا إلى إعادة تعيين عدد الإحالات لجميع الأطباء إلى 0. لا يمكن التراجع عن هذا الإجراء.',
      uncheckPartnersTitle: 'هل أنت متأكد؟',
      uncheckPartnersDesc: 'سيؤدي هذا إلى إزالة حالة الشريك من جميع الأطباء. لا يمكن التراجع عن هذا الإجراء.',
      deleteDoctorTitle: 'حذف الطبيب؟',
      deleteDoctorDesc: 'هل أنت متأكد من أنك تريد حذف هذا الطبيب؟ لا يمكن التراجع عن هذا الإجراء.',
      aboutTitle: 'عن روح',
      aboutDesc: 'صُنع بعناية لتبسيط حياتك المهنية، مما يتيح لك إدارة دليل الأطباء الخاص بك بسهولة وكفاءة.',
      contactOwner: 'للاستفسار أو تقديم اقتراحات، تواصل مع صاحب المشروع:',
      chatTitle: 'مساعد طبي بالذكاء الاصطناعي',
      chatPlaceholder: 'اطرح سؤالاً...',
      chatWelcome: 'أهلاً بك! كيف يمكنني مساعدتك اليوم؟',
      internetSearchTitle: 'بحث في الإنترنت عن أطباء',
      internetSearchDesc: 'استخدم الذكاء الاصطناعي للبحث عن أطباء عبر الإنترنت بناءً على الاسم، التخصص، المدينة، إلخ.',
      internetSearchPlaceholder: 'مثال: "طبيب قلب في بغداد"، "رقم هاتف دكتور علي"...',
      internetSearching: 'يقوم الذكاء الاصطناعي بالبحث في الإنترنت عن الأطباء...',
      addAllResults: 'إضافة كل النتائج ({count})',
    },
    toasts: {
      offline: 'أنت غير متصل بالإنترنت. بعض الميزات قد لا تكون متاحة.',
      online: 'لقد عدت متصلاً بالإنترنت.',
      locationError: 'تعذر الحصول على الموقع. يرجى تفعيل خدمات الموقع.',
      exportSuccess: 'تم تصدير البيانات بنجاح!',
      exportError: 'فشل تصدير البيانات.',
      importSuccess: 'تم استيراد البيانات بنجاح!',
      importError: 'فشل استيراد البيانات من الملف.',
      exporting: 'جاري التصدير...',
      exportingDesc: 'يرجى الانتظار بينما يتم تجهيز البيانات.',
      searchErrorTitle: 'فشل البحث',
      searchErrorDesc: 'فشل بحث الذكاء الاصطناعي. يرجى المحاولة مرة أخرى لاحقًا.',
      doctorAddedTitle: 'تمت إضافة الطبيب',
      doctorAddedDesc: 'تمت إضافته إلى قائمتك المحلية.',
      allDoctorsAddedTitle: 'تمت إضافة جميع الأطباء',
      allDoctorsAddedDesc: 'تمت إضافة {count} أطباء إلى قائمتك المحلية.',
      noDataToExport: 'لا توجد بيانات لتصديرها.',
    },
    common: {
      loading: 'جار التحميل...',
      noResults: 'لم يتم العثور على نتائج. حاول البحث بكلمات مختلفة.',
      add: 'إضافة',
      search: 'بحث',
      close: 'إغلاق',
    },
    admin: {
      dashboardTitle: 'لوحة تحكم المسؤول',
      usersTable: 'المستخدمون المسجلون',
      username: 'اسم المستخدم',
      phoneNumber: 'رقم الهاتف',
      role: 'الدور',
      actions: 'الإجراءات',
      addUser: 'إضافة مستخدم',
      makeAdmin: 'جعله مسؤولاً',
      removeAdmin: 'إزالة المسؤول',
      deleteUserTitle: 'حذف المستخدم؟',
      deleteUserDesc: 'هل أنت متأكد أنك تريد حذف هذا المستخدم',
      addUserDialogTitle: 'إضافة مستخدم جديد',
      editUserDialogTitle: 'تعديل مستخدم',
      saveChanges: 'حفظ التغييرات',
      editUserSuccess: 'تم تحديث المستخدم بنجاح',
      editUserError: 'فشل تحديث المستخدم. قد يكون البريد الإلكتروني أو رقم الهاتف موجوداً بالفعل.',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      addUserSuccess: 'تمت إضافة المستخدم بنجاح',
      addUserError: 'فشل في إضافة المستخدم',
    },
    partnerDashboard: {
      description: 'نظرة سريعة على الأطباء الشركاء وإحالاتهم.',
      editReferrals: 'تعديل الإحالات',
      noPartners: 'ليس لديك أطباء شركاء بعد.',
      exportExcel: 'تصدير Excel',
      close: 'إغلاق',
    },
    referralNotes: {
      title: "ملاحظات حالات الإحالة",
      description: "ملاحظات للحالات المحالة من الدكتور {name}",
      caseLabel: "الحالة رقم {index}",
      save: "حفظ الملاحظات",
      noCases: "لا توجد إحالات لعرضها. قم بزيادة عدد الإحالات لإضافة ملاحظات.",
      patientName: "اسم المريض",
      referralDate: "تاريخ التحويل",
      testType: "نوع الفحص",
      patientAge: "عمر المريض",
      chronicDiseases: "الأمراض المزمنة",
      chronicDiseasesPlaceholder: "مثال: سكري، ضغط الدم",
      manageCases: "إدارة الحالات",
      addCase: "إضافة حالة",
      removeCase: "حذف آخر حالة",
    },
    doctorList: {
      name: 'الاسم',
      specialty: 'التخصص',
      actions: 'الإجراءات',
    }
  },
};
