
import { Doctor } from '@/types';

// This file is intentionally left empty for production.
// Mock data can be added here for development purposes.
export const MOCK_DOCTORS: Omit<Doctor, 'id' | 'createdAt'>[] = [
  {
    name: "Dr. Ahmed Al-Jumaily",
    specialty: "Cardiology",
    phoneNumber: "07701234567",
    clinicAddress: "Al-Mansour, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 15,
    availableDays: ["Sat", "Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Fatima Al-Zubaidi",
    specialty: "Dermatology",
    phoneNumber: "07807654321",
    clinicAddress: "Al-Karrada, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 5,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Yusuf Al-Haddad",
    specialty: "Orthopedics",
    phoneNumber: "07901122334",
    clinicAddress: "Al-Adhamiyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 25,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Layla Al-Khafaji",
    specialty: "Pediatrics",
    phoneNumber: "07712345678",
    clinicAddress: "Zayouna, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 8,
    availableDays: ["Mon", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Omar Al-Tikriti",
    specialty: "Neurology",
    phoneNumber: "07818765432",
    clinicAddress: "Yarmouk, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 12,
    availableDays: ["Sun", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Noor Al-Shammari",
    specialty: "Oncology",
    phoneNumber: "07912233445",
    clinicAddress: "Medical City, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 3,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Ali Al-Saadi",
    specialty: "General Surgery",
    phoneNumber: "07723456789",
    clinicAddress: "Al-Harthiya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 30,
    availableDays: ["Tue", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Huda Al-Abadi",
    specialty: "Gynecology",
    phoneNumber: "07829876543",
    clinicAddress: "Al-Jadriya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 22,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Ibrahim Al-Dulaimi",
    specialty: "Urology",
    phoneNumber: "07923344556",
    clinicAddress: "Amiriyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 18,
    availableDays: ["Mon", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Mariam Al-Yasiri",
    specialty: "Ophthalmology",
    phoneNumber: "07734567890",
    clinicAddress: "Palestine Street, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 11,
    availableDays: ["Tue", "Wed", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Khalid Al-Amiri",
    specialty: "ENT",
    phoneNumber: "07830987654",
    clinicAddress: "Al-Saydiya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 9,
    availableDays: ["Sat", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Zainab Al-Rubaie",
    specialty: "Internal Medicine",
    phoneNumber: "07934455667",
    clinicAddress: "Al-Dora, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 14,
    availableDays: ["Sun", "Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Mustafa Al-Janabi",
    specialty: "Psychiatry",
    phoneNumber: "07745678901",
    clinicAddress: "Bab Al-Moatham, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 6,
    availableDays: ["Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Sarah Al-Bayati",
    specialty: "Rheumatology",
    phoneNumber: "07849876543",
    clinicAddress: "Al-Waziriyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 4,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Hassan Al-Maliki",
    specialty: "Gastroenterology",
    phoneNumber: "07945566778",
    clinicAddress: "Al-Ghazaliyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 19,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Aisha Al-Rawi",
    specialty: "Endocrinology",
    phoneNumber: "07756789012",
    clinicAddress: "Al-Mansour, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 7,
    availableDays: ["Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Abdullah Al-Ani",
    specialty: "Pulmonology",
    phoneNumber: "07850987654",
    clinicAddress: "Al-Karrada, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 13,
    availableDays: ["Sat", "Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Rania Al-Tai",
    specialty: "Nephrology",
    phoneNumber: "07956677889",
    clinicAddress: "Medical City, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 10,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Fares Al-Qaisi",
    specialty: "Family Medicine",
    phoneNumber: "07767890123",
    clinicAddress: "Hay Al-Jami'a, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 20,
    availableDays: ["Sun", "Tue", "Wed", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Dina Al-Musawi",
    specialty: "Emergency Medicine",
    phoneNumber: "07869876543",
    clinicAddress: "Ibn Al-Nafees Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 0,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Mahmoud Al-Sultani",
    specialty: "Cardiology",
    phoneNumber: "07967788990",
    clinicAddress: "Basra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 12,
    availableDays: ["Sat", "Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Samira Al-Basri",
    specialty: "Dermatology",
    phoneNumber: "07778901234",
    clinicAddress: "Erbil",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 22,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Jawad Al-Mosuli",
    specialty: "Orthopedics",
    phoneNumber: "07876543210",
    clinicAddress: "Mosul",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 17,
    availableDays: ["Mon", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Iman Al-Najafi",
    specialty: "Pediatrics",
    phoneNumber: "07978899001",
    clinicAddress: "Najaf",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 35,
    availableDays: ["Sat", "Sun", "Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Hadi Al-Karbalai",
    specialty: "Neurology",
    phoneNumber: "07789012345",
    clinicAddress: "Karbala",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 9,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Salwa Al-Hilli",
    specialty: "Oncology",
    phoneNumber: "07887654321",
    clinicAddress: "Hilla",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 5,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Karim Al-Diwani",
    specialty: "General Surgery",
    phoneNumber: "07989900112",
    clinicAddress: "Diwaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 28,
    availableDays: ["Tue", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Asma Al-Ramadi",
    specialty: "Gynecology",
    phoneNumber: "07790123456",
    clinicAddress: "Ramadi",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 16,
    availableDays: ["Sun", "Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Bashir Al-Samarrai",
    specialty: "Urology",
    phoneNumber: "07898765432",
    clinicAddress: "Samarra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 14,
    availableDays: ["Mon", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Ghada Al-Kirkuki",
    specialty: "Ophthalmology",
    phoneNumber: "07990011223",
    clinicAddress: "Kirkuk",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 11,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Saad Al-Dohuki",
    specialty: "ENT",
    phoneNumber: "07701122334",
    clinicAddress: "Duhok",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 8,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Afra Al-Sulaimani",
    specialty: "Internal Medicine",
    phoneNumber: "07802233445",
    clinicAddress: "Sulaymaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 24,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Tariq Al-Amari",
    specialty: "Psychiatry",
    phoneNumber: "07903344556",
    clinicAddress: "Amarah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 7,
    availableDays: ["Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Wafa Al-Nasiri",
    specialty: "Rheumatology",
    phoneNumber: "07714455667",
    clinicAddress: "Nasiriyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 3,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Jamal Al-Kuti",
    specialty: "Gastroenterology",
    phoneNumber: "07815566778",
    clinicAddress: "Kut",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 19,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Nihad Al-Baqubi",
    specialty: "Endocrinology",
    phoneNumber: "07916677889",
    clinicAddress: "Baqubah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 9,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Adnan Al-Falluji",
    specialty: "Pulmonology",
    phoneNumber: "07727788990",
    clinicAddress: "Fallujah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 15,
    availableDays: ["Sat", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Nadia Al-Samawi",
    specialty: "Nephrology",
    phoneNumber: "07828899001",
    clinicAddress: "Samawah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 12,
    availableDays: ["Sun", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Qasim Al-Zubairi",
    specialty: "Family Medicine",
    phoneNumber: "07929900112",
    clinicAddress: "Al-Zubair",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 25,
    availableDays: ["Mon", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Maysam Al-Kadhimi",
    specialty: "Emergency Medicine",
    phoneNumber: "07730011223",
    clinicAddress: "Kadhimiya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 1,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Saif Al-Hayani",
    specialty: "Cardiology",
    phoneNumber: "07700112233",
    clinicAddress: "Hay Al-Adel, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 14,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Lina Al-Hashimi",
    specialty: "Dermatology",
    phoneNumber: "07801223344",
    clinicAddress: "Hay Al-Amil, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 21,
    availableDays: ["Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Akram Al-Obeidi",
    specialty: "Orthopedics",
    phoneNumber: "07902334455",
    clinicAddress: "Al-Bayaa, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 16,
    availableDays: ["Sat", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Raghad Al-Jibouri",
    specialty: "Pediatrics",
    phoneNumber: "07713445566",
    clinicAddress: "Al-Ameria, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 33,
    availableDays: ["Sun", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Faris Al-Nuaimi",
    specialty: "Neurology",
    phoneNumber: "07814556677",
    clinicAddress: "Al-Khadra, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 10,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Ban Al-Daghistani",
    specialty: "Oncology",
    phoneNumber: "07915667788",
    clinicAddress: "Al-Kindi Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 6,
    availableDays: ["Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Ghassan Al-Shara",
    specialty: "General Surgery",
    phoneNumber: "07726778899",
    clinicAddress: "Al-Yarmouk Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 29,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Dalia Al-Zahawi",
    specialty: "Gynecology",
    phoneNumber: "07827889900",
    clinicAddress: "Al-Elwiya Maternity Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 26,
    availableDays: ["Mon", "Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Luay Al-Safi",
    specialty: "Urology",
    phoneNumber: "07928990011",
    clinicAddress: "Al-Karama Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 15,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Marwa Al-Baghdadi",
    specialty: "Ophthalmology",
    phoneNumber: "07739001122",
    clinicAddress: "Ibn Al-Haitham Teaching Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 13,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Raed Al-Askari",
    specialty: "Cardiology",
    phoneNumber: "07831122334",
    clinicAddress: "Ibn Al-Bitar Cardiac Center, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 20,
    availableDays: ["Mon", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Hanan Al-Moussawi",
    specialty: "Dermatology",
    phoneNumber: "07932233445",
    clinicAddress: "Al-Mansour, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 2,
    availableDays: ["Sat", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Ammar Al-Hamdani",
    specialty: "Orthopedics",
    phoneNumber: "07743344556",
    clinicAddress: "Al-Karkh, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 19,
    availableDays: ["Sun", "Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Israa Al-Fahdawi",
    specialty: "Pediatrics",
    phoneNumber: "07844455667",
    clinicAddress: "Al-Iskan, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 40,
    availableDays: ["Mon", "Wed", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Bassam Al-Kubaisi",
    specialty: "Neurology",
    phoneNumber: "07945566778",
    clinicAddress: "Neurosciences Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 11,
    availableDays: ["Tue", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Jinan Al-Timimi",
    specialty: "Oncology",
    phoneNumber: "07756677889",
    clinicAddress: "Al-Amal National Hospital for Cancer Management, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 8,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Waddah Al-Khazraji",
    specialty: "General Surgery",
    phoneNumber: "07857788990",
    clinicAddress: "Baghdad Teaching Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 31,
    availableDays: ["Mon", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Maysoun Al-Sadr",
    specialty: "Gynecology",
    phoneNumber: "07958899001",
    clinicAddress: "Hayy Ur, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 23,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Salam Al-Sharafi",
    specialty: "Urology",
    phoneNumber: "07769900112",
    clinicAddress: "Al-Shaab, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 16,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Reem Al-Gailani",
    specialty: "Ophthalmology",
    phoneNumber: "07870011223",
    clinicAddress: "Baghdad Al-Jadeeda, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 14,
    availableDays: ["Sun", "Mon", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Thaer Al-Badri",
    specialty: "ENT",
    phoneNumber: "07971122334",
    clinicAddress: "Al-Hurriya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 10,
    availableDays: ["Mon", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Sundus Al-Azzawi",
    specialty: "Internal Medicine",
    phoneNumber: "07782233445",
    clinicAddress: "Al-Kifah Street, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 27,
    availableDays: ["Sun", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Laith Al-Faraji",
    specialty: "Psychiatry",
    phoneNumber: "07883344556",
    clinicAddress: "Ibn Rushd Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 5,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Walaa Al-Obaidi",
    specialty: "Rheumatology",
    phoneNumber: "07984455667",
    clinicAddress: "Al-Wasiti, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 4,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Mazin Al-Douri",
    specialty: "Gastroenterology",
    phoneNumber: "07795566778",
    clinicAddress: "Gastroenterology and Hepatology Teaching Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 20,
    availableDays: ["Tue", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Aseel Al-Saeedi",
    specialty: "Endocrinology",
    phoneNumber: "07896677889",
    clinicAddress: "The National Center for Diabetes, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 11,
    availableDays: ["Sun", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Qahtan Al-Anbari",
    specialty: "Pulmonology",
    phoneNumber: "07997788990",
    clinicAddress: "Al-Anbar",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 17,
    availableDays: ["Mon", "Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Eman Al-Zangana",
    specialty: "Nephrology",
    phoneNumber: "07708899001",
    clinicAddress: "Diyala",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 13,
    availableDays: ["Sun", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Haider Al-Shibli",
    specialty: "Family Medicine",
    phoneNumber: "07809900112",
    clinicAddress: "Babil",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 24,
    availableDays: ["Mon", "Tue", "Wed", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Farah Al-Barzanji",
    specialty: "Emergency Medicine",
    phoneNumber: "07910011223",
    clinicAddress: "Erbil Emergency Hospital, Erbil",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 2,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Muhannad Al-Iraqi",
    specialty: "Cardiology",
    phoneNumber: "07711223344",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 18,
    availableDays: ["Sat", "Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Zainab Al-Baghdadi",
    specialty: "Dermatology",
    phoneNumber: "07812334455",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 23,
    availableDays: ["Sun", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Ali Al-Mansouri",
    specialty: "Orthopedics",
    phoneNumber: "07913445566",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 20,
    availableDays: ["Mon", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Fatima Al-Karkhi",
    specialty: "Pediatrics",
    phoneNumber: "07724556677",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 38,
    availableDays: ["Tue", "Wed", "Sun"],
    referralNotes: []
  },
  {
    name: "Dr. Omar Al-Rusafi",
    specialty: "Neurology",
    phoneNumber: "07825667788",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 12,
    availableDays: ["Mon", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Nora Al-Adhami",
    specialty: "Oncology",
    phoneNumber: "07926778899",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 7,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Yasser Al-Jadiri",
    specialty: "General Surgery",
    phoneNumber: "07737889900",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 33,
    availableDays: ["Wed", "Sat", "Sun"],
    referralNotes: []
  },
  {
    name: "Dr. Sara Al-Amiri",
    specialty: "Gynecology",
    phoneNumber: "07838990011",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 28,
    availableDays: ["Mon", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Abbas Al-Yassiri",
    specialty: "Urology",
    phoneNumber: "07939001122",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 17,
    availableDays: ["Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Hiba Al-Jumaily",
    specialty: "Ophthalmology",
    phoneNumber: "07740112233",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 15,
    availableDays: ["Sun", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Firas Al-Zubaidi",
    specialty: "ENT",
    phoneNumber: "07841223344",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 12,
    availableDays: ["Mon", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Lana Al-Haddad",
    specialty: "Internal Medicine",
    phoneNumber: "07942334455",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 29,
    availableDays: ["Tue", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Zaid Al-Khafaji",
    specialty: "Psychiatry",
    phoneNumber: "07753445566",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 6,
    availableDays: ["Thu", "Sun"],
    referralNotes: []
  },
  {
    name: "Dr. Rawan Al-Tikriti",
    specialty: "Rheumatology",
    phoneNumber: "07854556677",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 5,
    availableDays: ["Mon", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Majid Al-Shammari",
    specialty: "Gastroenterology",
    phoneNumber: "07955667788",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 22,
    availableDays: ["Tue", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Asil Al-Saadi",
    specialty: "Endocrinology",
    phoneNumber: "07766778899",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 13,
    availableDays: ["Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Fahad Al-Abadi",
    specialty: "Pulmonology",
    phoneNumber: "07867889900",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 19,
    availableDays: ["Thu", "Sun"],
    referralNotes: []
  },
  {
    name: "Dr. Rasha Al-Dulaimi",
    specialty: "Nephrology",
    phoneNumber: "07968990011",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 14,
    availableDays: ["Mon", "Tue"],
    referralNotes: []
  },
  {
    name: "Dr. Iyad Al-Yasiri",
    specialty: "Family Medicine",
    phoneNumber: "07779001122",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 30,
    availableDays: ["Wed", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Sura Al-Amiri",
    specialty: "Emergency Medicine",
    phoneNumber: "07880112233",
    clinicAddress: "Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 3,
    availableDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Kamal Al-Bayati",
    specialty: "Cardiology",
    phoneNumber: "07981223344",
    clinicAddress: "Basra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 16,
    availableDays: ["Mon", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Jamila Al-Maliki",
    specialty: "Dermatology",
    phoneNumber: "07792334455",
    clinicAddress: "Erbil",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 25,
    availableDays: ["Tue", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Safaa Al-Janabi",
    specialty: "Orthopedics",
    phoneNumber: "07893445566",
    clinicAddress: "Mosul",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 21,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Amer Al-Rubaie",
    specialty: "Pediatrics",
    phoneNumber: "07994556677",
    clinicAddress: "Najaf",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 42,
    availableDays: ["Mon", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Batoul Al-Sultani",
    specialty: "Neurology",
    phoneNumber: "07705667788",
    clinicAddress: "Karbala",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 13,
    availableDays: ["Tue", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Ghazi Al-Basri",
    specialty: "Oncology",
    phoneNumber: "07806778899",
    clinicAddress: "Hilla",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 9,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Muna Al-Mosuli",
    specialty: "General Surgery",
    phoneNumber: "07907889900",
    clinicAddress: "Diwaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 35,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Nawal Al-Najafi",
    specialty: "Gynecology",
    phoneNumber: "07718990011",
    clinicAddress: "Ramadi",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 30,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Qais Al-Karbalai",
    specialty: "Urology",
    phoneNumber: "07819001122",
    clinicAddress: "Samarra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 20,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Sabah Al-Hilli",
    specialty: "Ophthalmology",
    phoneNumber: "07920112233",
    clinicAddress: "Kirkuk",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 17,
    availableDays: ["Sun", "Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Hameed Al-Diwani",
    specialty: "ENT",
    phoneNumber: "07721223344",
    clinicAddress: "Duhok",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 14,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Ibtisam Al-Ramadi",
    specialty: "Internal Medicine",
    phoneNumber: "07822334455",
    clinicAddress: "Sulaymaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 32,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Wissam Al-Samarrai",
    specialty: "Psychiatry",
    phoneNumber: "07923445566",
    clinicAddress: "Amarah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 8,
    availableDays: ["Sun", "Mon"],
    referralNotes: []
  },
  {
    name: "Dr. Zain Al-Kirkuki",
    specialty: "Rheumatology",
    phoneNumber: "07734556677",
    clinicAddress: "Nasiriyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 6,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Riyad Al-Dohuki",
    specialty: "Gastroenterology",
    phoneNumber: "07835667788",
    clinicAddress: "Kut",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 24,
    availableDays: ["Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Azhar Al-Sulaimani",
    specialty: "Endocrinology",
    phoneNumber: "07936778899",
    clinicAddress: "Baqubah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 15,
    availableDays: ["Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Jafar Al-Amari",
    specialty: "Pulmonology",
    phoneNumber: "07747889900",
    clinicAddress: "Fallujah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 20,
    availableDays: ["Sun", "Mon"],
    referralNotes: []
  },
  {
    name: "Dr. Suha Al-Nasiri",
    specialty: "Nephrology",
    phoneNumber: "07848990011",
    clinicAddress: "Samawah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 16,
    availableDays: ["Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Omar Al-Kuti",
    specialty: "Family Medicine",
    phoneNumber: "07949001122",
    clinicAddress: "Al-Zubair",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 36,
    availableDays: ["Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Maryam Al-Baqubi",
    specialty: "Emergency Medicine",
    phoneNumber: "07750112233",
    clinicAddress: "Kadhimiya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 4,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Hussein Al-Falluji",
    specialty: "Cardiology",
    phoneNumber: "07851223344",
    clinicAddress: "Hay Al-Adel, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 22,
    availableDays: ["Sun", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Isra Al-Samawi",
    specialty: "Dermatology",
    phoneNumber: "07952334455",
    clinicAddress: "Hay Al-Amil, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 27,
    availableDays: ["Mon", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Taha Al-Zubairi",
    specialty: "Orthopedics",
    phoneNumber: "07763445566",
    clinicAddress: "Al-Bayaa, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 23,
    availableDays: ["Tue", "Wed", "Sun"],
    referralNotes: []
  },
  {
    name: "Dr. Dunya Al-Kadhimi",
    specialty: "Pediatrics",
    phoneNumber: "07864556677",
    clinicAddress: "Al-Ameria, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 45,
    availableDays: ["Mon", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Karam Al-Hayani",
    specialty: "Neurology",
    phoneNumber: "07965667788",
    clinicAddress: "Al-Khadra, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 15,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Luma Al-Hashimi",
    specialty: "Oncology",
    phoneNumber: "07776778899",
    clinicAddress: "Al-Kindi Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 10,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Adam Al-Obeidi",
    specialty: "General Surgery",
    phoneNumber: "07877889900",
    clinicAddress: "Al-Yarmouk Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 38,
    availableDays: ["Sun", "Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Rana Al-Jibouri",
    specialty: "Gynecology",
    phoneNumber: "07978990011",
    clinicAddress: "Al-Elwiya Maternity Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 33,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Malik Al-Nuaimi",
    specialty: "Urology",
    phoneNumber: "07789001122",
    clinicAddress: "Al-Karama Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 22,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Saja Al-Daghistani",
    specialty: "Ophthalmology",
    phoneNumber: "07880112233",
    clinicAddress: "Ibn Al-Haitham Teaching Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 19,
    availableDays: ["Sun", "Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Basel Al-Zahawi",
    specialty: "ENT",
    phoneNumber: "07981223344",
    clinicAddress: "Al-Saydiya, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 16,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Diana Al-Safi",
    specialty: "Internal Medicine",
    phoneNumber: "07792334455",
    clinicAddress: "Al-Dora, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 35,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Hamza Al-Baghdadi",
    specialty: "Psychiatry",
    phoneNumber: "07893445566",
    clinicAddress: "Bab Al-Moatham, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 9,
    availableDays: ["Sun", "Mon"],
    referralNotes: []
  },
  {
    name: "Dr. Haneen Al-Askari",
    specialty: "Rheumatology",
    phoneNumber: "07994556677",
    clinicAddress: "Al-Waziriyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 7,
    availableDays: ["Tue", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Othman Al-Moussawi",
    specialty: "Gastroenterology",
    phoneNumber: "07705667788",
    clinicAddress: "Al-Ghazaliyah, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 26,
    availableDays: ["Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Ahlam Al-Hamdani",
    specialty: "Endocrinology",
    phoneNumber: "07806778899",
    clinicAddress: "Al-Mansour, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 14,
    availableDays: ["Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Ziyad Al-Fahdawi",
    specialty: "Pulmonology",
    phoneNumber: "07907889900",
    clinicAddress: "Al-Karrada, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 21,
    availableDays: ["Sun", "Mon"],
    referralNotes: []
  },
  {
    name: "Dr. Yasmin Al-Kubaisi",
    specialty: "Nephrology",
    phoneNumber: "07718990011",
    clinicAddress: "Medical City, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 18,
    availableDays: ["Tue", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Nizar Al-Timimi",
    specialty: "Family Medicine",
    phoneNumber: "07819001122",
    clinicAddress: "Hay Al-Jami'a, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 39,
    availableDays: ["Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Asmaa Al-Khazraji",
    specialty: "Emergency Medicine",
    phoneNumber: "07920112233",
    clinicAddress: "Ibn Al-Nafees Hospital, Baghdad",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 5,
    availableDays: ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Amjad Al-Sharafi",
    specialty: "Cardiology",
    phoneNumber: "07721223344",
    clinicAddress: "Basra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 19,
    availableDays: ["Mon", "Wed", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Taghreed Al-Gailani",
    specialty: "Dermatology",
    phoneNumber: "07822334455",
    clinicAddress: "Erbil",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 28,
    availableDays: ["Tue", "Thu", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Rafeef Al-Badri",
    specialty: "Orthopedics",
    phoneNumber: "07923445566",
    clinicAddress: "Mosul",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 24,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Aws Al-Azzawi",
    specialty: "Pediatrics",
    phoneNumber: "07734556677",
    clinicAddress: "Najaf",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 48,
    availableDays: ["Mon", "Thu", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Rayan Al-Faraji",
    specialty: "Neurology",
    phoneNumber: "07835667788",
    clinicAddress: "Karbala",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 16,
    availableDays: ["Tue", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Susan Al-Obaidi",
    specialty: "Oncology",
    phoneNumber: "07936778899",
    clinicAddress: "Hilla",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 11,
    availableDays: ["Sun", "Wed"],
    referralNotes: []
  },
  {
    name: "Dr. Wissam Al-Douri",
    specialty: "General Surgery",
    phoneNumber: "07747889900",
    clinicAddress: "Diwaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 40,
    availableDays: ["Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Lubna Al-Saeedi",
    specialty: "Gynecology",
    phoneNumber: "07848990011",
    clinicAddress: "Ramadi",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 35,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Muthanna Al-Anbari",
    specialty: "Urology",
    phoneNumber: "07949001122",
    clinicAddress: "Samarra",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 23,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  },
  {
    name: "Dr. Anwar Al-Zangana",
    specialty: "Ophthalmology",
    phoneNumber: "07750112233",
    clinicAddress: "Kirkuk",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 20,
    availableDays: ["Sun", "Mon", "Thu"],
    referralNotes: []
  },
  {
    name: "Dr. Salah Al-Shibli",
    specialty: "ENT",
    phoneNumber: "07851223344",
    clinicAddress: "Duhok",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: false,
    referralCount: 18,
    availableDays: ["Tue", "Fri"],
    referralNotes: []
  },
  {
    name: "Dr. Nagham Al-Barzanji",
    specialty: "Internal Medicine",
    phoneNumber: "07952334455",
    clinicAddress: "Sulaymaniyah",
    mapLocation: "",
    clinicCardImageUrl: "",
    isPartner: true,
    referralCount: 38,
    availableDays: ["Wed", "Sat"],
    referralNotes: []
  }
];
